### ISSUE TITLE
Crash on `MicrophoneAudioSource.read()`

### ISSUE THREAD

**Issue by KannebTo** [juanmc2005/StreamingSpeakerDiarization#10]
I have an issue with the audio access with the example code from the README, probably due to my audio setup:
```
>>> mic.read()
torch.Size([4, 512])
python: src/hostapi/alsa/pa_linux_alsa.c:3641: PaAlsaStreamComponent_BeginPolling: Assertion `ret == self->nfds' failed.
Aborted (core dumped)
```
This is strange because I'm running this in a Docker container and I also use the `sounddevice` library without problems in another project in the same container.

_Originally posted by @KannebTo in https://github.com/juanmc2005/StreamingSpeakerDiarization/issues/8#issuecomment-949453753_

**Comment by juanmc2005** [comment]
This should be solved in #19. Feel free to reopen if needed.
