### ISSUE TITLE
Changes to files not taking effect

### ISSUE THREAD

**Issue by jason-daiuto** [juanmc2005/StreamingSpeakerDiarization#111]
I'm relatively inexperienced when it comes to Python

when I make changes to the source code, none of the changes take effect when I run the script.

I've been trying to find solutions for days and I have had no luck.

Is it something specific to this project that is preventing changes from being made?

For instance, I simply tried to change the output of the print statement for the reports that are being printed in the console after the plot window is closed and even the simplest change is not taking effect.

Any help would be GREATLY appreciated, Thank You!

**Comment by juanmc2005** [comment]
Hi @jason-daiuto,

This seems like a python question unrelated to diart. I recommend you fork and clone the project and install it with `pip install -e <project_root_dir>`.
This will install your copy and be aware of the changes you make.
