### ISSUE TITLE
Error while using diart.stream for file

### ISSUE THREAD

**Issue by ankurdhuriya** [juanmc2005/StreamingSpeakerDiarization#114]
FileNotFoundError: [Errno 2] No such file or directory: 'test.rttm'
Streaming test: 0chunk [00:00, ?chunk/s]

**Comment by juanmc2005** [comment]
Hi @ankurdhuriya, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I can't seem to reproduce your error using v0.6.
