### ISSUE TITLE
Where the output will be saved after using diart.stream microphone OR when will it stop recording ?

### ISSUE THREAD

**Issue by ankurdhuriya** [juanmc2005/StreamingSpeakerDiarization#117]

**Comment by m15kh** [comment]
hi @ankurdhuriya 
you silved this issue?
if yes
can you explain how did you do it

**Comment by juanmc2005** [comment]
Hello,

The default output of `diart.stream microphone` is your home directory.
Here's an extract of `diart.stream -h`:
```
--output OUTPUT       Directory to store the system's output in RTTM format. Defaults to home directory if SOURCE == 'microphone' or parent directory if SOURCE is a file
```

It will stop recording as soon as the process ends or is killed.
