### ISSUE TITLE
Returning real time annotations 

### ISSUE THREAD

**Issue by ukemamaster** [juanmc2005/StreamingSpeakerDiarization#119]
I am new to RxPy. I want to return the real time annotaions values to the API. The real time annotaions happen to be in `DiarizationPredictionAccumulator()` class's `on_next()` method. However in the `Inference()` class's, `__call__()` method, it only returns  `self.accumulator.get_prediction()` which is the final result of the whole audio. 
Is there a way to return the annotation in real time (and not at the end)?

**Comment by juanmc2005** [comment]
Hi @ukemamaster,

There are indeed two ways to obtain the diarization prediction.
As you mention, if you wait for the stream to finish, the call to `Inference.__call__()` will return the entire annotation (provided that the audio source `read()` method is blocking, which needs to be fixed in a future version).

The way in which you receive prediction "pieces" in real time is through the RxPY stream, which `Inference` hides from you for convenience.
If you want to execute a piece of code whenever a new real-time prediction is available, you can register a hook function:

```python
from diart import OnlineSpeakerDiarization
from diart.sources import MicrophoneAudioSource
from diart.inference import RealTimeInference
from diart.sinks import RTTMWriter

def use_real_time_prediction(prediction, waveform):
    # do something here
    pass

pipeline = OnlineSpeakerDiarization()
mic = MicrophoneAudioSource(pipeline.config.sample_rate)
inference = RealTimeInference(pipeline, mic, do_plot=True)

# the function will be called with each new prediction in real time
inference.attach_hooks(use_real_time_prediction)

total_prediction = inference()
``` 

This way the `Inference` class will take care of handling the RxPY side for you so that it calls `use_real_time_prediction`.

Hope this answers your question.

**Comment by ukemamaster** [comment]
Thanks @juanmc2005 , 
Using this i can access the real time annotations inside `use_real_time_prediction` function but the problem is that i cannot return them in a gRPC response (which is the ultimate goal), since i am returning from the API after the `total_prediction` = `inference()` call, but the compiler stays here until the whole audio is done, and it keeps calling the `use_real_time_prediction` function. Any idea to acheive this?

Here is my gRPC server: 

```
class SpeakerServicer(speakerdiarization_pb2_grpc.SpeakerServicer):
    def __init__(self,num_workers,host,port):
       self.host = host 
       self.port = port
       if num_workers is None:
          self.num_workers = os.cpu_count()
       else:
          self.num_workers = num_workers
       self.display_values = False

    def SpeakerDiarization(self, request, context):
         self.request = next(request)
         _LOGGER_.info(f'grpc Request received')
         gc.collect()
         try:
           segmentation = SegmentationModel.from_pyannote("pyannote/segmentation", token)
           embedding = EmbeddingModel.from_pyannote("pyannote/embedding", token)
           config = PipelineConfig(segmentation=segmentation, embedding=embedding)
           pipeline = OnlineSpeakerDiarization(config)

           mic = grpcAudioSource(request, context, pipeline.config.sample_rate)
           inference = RealTimeInference(_LOGGER_, pipeline, mic, do_plot=False, display_values=False,  show_progress=False)
           inference.attach_observers(RTTMWriter(mic.uri, f"results/{mic.uri}.rttm"))

           def use_real_time_prediction(prediction):
               self.annotation = str(prediction[0])
               if self.display_values:
                  _LOGGER_.info(f'Result time stamps for uid [{self.request.uid}] : {self.annotation}')
               try:
                  self.response = gRPC_speaker.SpeakerDiarizationResponse(
                                  uid = self.request.uid,
                                  rttm = self.annotation
                                  )
               except Exception as e:
                  self.logger.error(f'Response for uid [{self.request.uid}] not returened because of: {e}')
                  self.response = gRPC_speaker.SpeakerDiarizationResponse(
                                  uid = self.request.uid
                                  )

           a = inference.attach_hooks(use_real_time_prediction)
           responses = inference()
           while context.is_active():
                   yield self.response
           gc.collect()
         except Exception as e:
           _LOGGER_.info(f'Something is wrong - {e}')
```

**Comment by juanmc2005** [comment]
Ok so you need `inference()` to be non-blocking.
One thing you could try is to detach your server from the pipeline and make it asynchronous, similar to `WebSocketAudioSource` (which is both audio source and server).
At this point, you should have two separate loops: the server running in the background and the diarization pipeline on the main thread.

You should be able to get the same result with threads or with co-routines, but the important thing is that the server doesn't block the main thread.
Alternatively, you could try playing with RxPY schedulers to make the pipeline run in a separate thread.

**Comment by ukemamaster** [comment]
Hi @juanmc2005 

I have tried to run the pipeline in a separate thread (as you suggested) and the server (somehow) works (at least for 1 client at a time). 
For multiple requests at the same time, the problem is how to differentiate the predictions? Because the hook function (you mentioned above) is called for every request. and the `prediction` generated is anonymouse. Can we do something like this: 

```python
def use_real_time_prediction(prediction, waveform, unique_request_id):
    response[unique_request_id] = prediction
```
In othe words how to put any other information in the hook function arguments?

**Comment by ukemamaster** [comment]
@juanmc2005 I have managed to associate the response with its corresponding request id using `queue.Queue()` like this: 

```python
response_queue = queue.Queue()
def get_prediction(prediction):
    response_queue.put(str(prediction[0]))

while context.is_active():
      response = response_queue.get()
      yield response
```
**Another question:** How to retrieve the images (resulting from annotations) from the `inference()` class to the hook function `use_real_time_prediction()` or another hook function?

**Comment by juanmc2005** [comment]
1) Keep in mind that the diarization system is stateful (aggregation buffer + speaker centroids), so you need to have a separate pipeline for each client (all the more reason to make them run in separate threads).

2) The images are built with `pyannote.core.notebook.plot_annotation(annotation)`, you don't need `Inference` for this. If your goal is to inspect predictions I recommend setting `do_plot=True`, but yes you can absolutely plot inside the hook (beware not to block the thread though).

**Comment by ukemamaster** [comment]
I am doing it this way: 
```python
def get_pipeline():
    segmentation = SegmentationModel.from_pyannote("pyannote/segmentation", token)
    embedding = EmbeddingModel.from_pyannote("pyannote/embedding", token)
    config = PipelineConfig(segmentation=segmentation, embedding=embedding)
    pipeline = OnlineSpeakerDiarization(config)
    return pipeline

for c in clients:
    pipeline = get_pipeline()
    mic = grpcAudioSource(_LOGGER_, request, context, pipeline.config.sample_rate)
    inference = RealTimeInference(_LOGGER_, pipeline, mic)
    c_predictions = inference()

```
For every client i am geting a new pipeline with `get_pipeline()` , is that OK?

**Comment by juanmc2005** [comment]
Looks good to me, just remember to run each pipeline in a background thread so you don't block the other clients.

**Comment by ukemamaster** [comment]
Yes. For every client the `get_inference()` fuction is run in a separate thread in the background. Works correctly. 

```python
def get_pipeline():
    segmentation = SegmentationModel.from_pyannote("pyannote/segmentation", token)
    embedding = EmbeddingModel.from_pyannote("pyannote/embedding", token)
    config = PipelineConfig(segmentation=segmentation, embedding=embedding)
    pipeline = OnlineSpeakerDiarization(config)
    return pipeline

def get_inference():
    pipeline = get_pipeline()
    mic = grpcAudioSource(_LOGGER_, request, context, pipeline.config.sample_rate)
    inference = RealTimeInference(_LOGGER_, pipeline, mic)
    predictions = inference()

for c in clients:
    inference_thread = Thread(target=get_inference)
    inference_thread.daemon = True
    inference_thread.start()

```

**Comment by juanmc2005** [comment]
Glad to hear it's working ! I'm closing the issue now since it's solved. Feel free to reopen if needed.

**Comment by ukemamaster** [comment]
@juanmc2005 One question: Only the pipeline is stateful? or the models also are stateful? 
In other words, can we do like this: 

```python
#call the model instances only once
segmentation = SegmentationModel.from_pyannote("pyannote/segmentation", token)
embedding = EmbeddingModel.from_pyannote("pyannote/embedding", token)

#call the pipeline genaration for each client
def get_pipeline():
    config = PipelineConfig(segmentation=segmentation, embedding=embedding)
    pipeline = OnlineSpeakerDiarization(config)
    return pipeline

for c in clients:
    pipeline = get_pipeline()
    mic = grpcAudioSource(_LOGGER_, request, context, pipeline.config.sample_rate)
    inference = RealTimeInference(_LOGGER_, pipeline, mic)
    c_predictions = inference()

```

**Comment by juanmc2005** [comment]
Yes the models are stateless so it would be even better to reuse them across threads.
If you have a GPU and many clients you could even optimize it further with a service that batches audio buffers for the model and then dispatches them to the respective pipelines.
It should be possible to implement it as a wrapper of `SegmentationModel` / `EmbeddingModel`.
