### ISSUE TITLE
 AttributeError: 'OnlineSpeakerDiarization' object has no attribute 'from_source'

### ISSUE THREAD

**Issue by kaleaniket** [juanmc2005/StreamingSpeakerDiarization#132]
Hello,
I am following this code for real-time speaker diarization -
 
from diart.sources import MicrophoneAudioSource
from diart import OnlineSpeakerDiarization
from diart.sinks import RealTimePlot
from diart.operators import buffer_output

duration, step, latency, sample_rate = 5, 0.5, 0.5, 16000
mic = MicrophoneAudioSource(sample_rate)
OnlineSpeakerDiarization().from_source(mic) \
    .pipe(buffer_output(duration, step, latency, sample_rate)) \
    .subscribe(RealTimePlot(duration, latency))

mic.read()

but got the error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_00000/00000000.py in <cell line: 8>()
      6 duration, step, latency, sample_rate = 5, 0.5, 0.5, 16000
      7 mic = MicrophoneAudioSource(sample_rate)
----> 8 OnlineSpeakerDiarization().from_source(mic) \
      9     .pipe(buffer_output(duration, step, latency, sample_rate)) \
     10     .subscribe(RealTimePlot(duration, latency))

**AttributeError: 'OnlineSpeakerDiarization' object has no attribute 'from_source'**

Is there any solution to this?

**Comment by juanmc2005** [comment]
Hi @kaleaniket,

You're following an old example from the README gif that I haven't had the time to update since the API changed.
You can try again using the example shown [here](https://github.com/juanmc2005/StreamingSpeakerDiarization#from-python)

**Comment by juanmc2005** [comment]
Related issue: #110

**Comment by kaleaniket** [comment]
> Hi @kaleaniket,
> 
> You're following an old example from the README gif that I haven't had the time to update since the API changed. You can try again using the example shown [here](https://github.com/juanmc2005/StreamingSpeakerDiarization#from-python)

Thank you that worked!! but only problem is that it doesn't visualize the output in real time. It shows the output for first chunk and after that it just shows **<Figure size 640x480 with 0 Axes>** for all of the other chunks.

**Comment by juanmc2005** [comment]
@kaleaniket could you share your code and output so I can see what's happening?

**Comment by kaleaniket** [comment]
> @kaleaniket could you share your code and output so I can see what's happening?

Yes, Sure @juanmc2005.
Here is it - 
![image](https://user-images.githubusercontent.com/69384682/225893704-0f5a787c-6505-40e4-9cfd-1f96599f1db9.png)
![image](https://user-images.githubusercontent.com/69384682/225893815-327177b1-ebb9-4f82-baf0-e87428229f0d.png)

**Comment by juanmc2005** [comment]
Ok I see the problem. the real-time plotting class is not compatible with notebooks yet.
A re-work of the plotting code is something that I've had in mind for a while now (see #76), but it's a bit tricky to implement so it's taking me some time.

For now, you can run the code from a separate python script, or you can use `diart.stream` from the command line.

In the future, I would like to make this compatible with standalone windows (already implemented), the browser and jupyter notebooks.

**Comment by kaleaniket** [comment]
> Ok I see the problem. the real-time plotting class is not compatible with notebooks yet. A re-work of the plotting code is something that I've had in mind for a while now (see #76), but it's a bit tricky to implement so it's taking me some time.
> 
> For now, you can run the code from a separate python script, or you can use `diart.stream` from the command line.
> 
> In the future, I would like to make this compatible with standalone windows (already implemented), the browser and jupyter notebooks.

Thank you @juanmc2005 that worked!
