### ISSUE TITLE
Any plan to release the model and training code?

### ISSUE THREAD

**Issue by kli017** [juanmc2005/StreamingSpeakerDiarization#14]
Nice work! Wondering if there any plan to release the code of training process and model?

**Comment by juanmc2005** [comment]
Hello! The short answer is yes.

Training the whole system is divided in two steps:
- pre-train the segmentation and speaker embedding models
- fine-tune hyper-parameters `tau`, `rho` and `delta`

For more information about the first step and how the models are trained see [here](https://huggingface.co/pyannote/segmentation) and [here](https://huggingface.co/pyannote/embedding). You'll need to install pyannote.audio 2.0 to train your own segmentation and embedding models.

For the second step, we plan to release a trainable version of the system as part of pyannote.audio 2.0 using the pyannote.pipeline interface but I'm still unsure about when it'll be made public.

**Comment by shipnight** [comment]
Thank you for your answer!This is very useful for me.I want to take the first step.But the first time I use huggingface, I don’t know how to use it.I want to know how can I use the information obtained from huggingface to train the model

**Comment by juanmc2005** [comment]
Hi @shipnight, I encourage you to take a look at [pyannote.audio 2.0](https://github.com/pyannote/pyannote-audio/tree/develop) (see "Low-level API") to train a model from scratch or fine-tune a Huggingface model.

I'm not sure what your use case is, but if you want to adapt the segmentation or embedding model to your dataset (not reproduce the results), the best would be to fine-tune the existing models.

**Comment by shipnight** [comment]
> Hi @shipnight, I encourage you to take a look at [pyannote.audio 2.0](https://github.com/pyannote/pyannote-audio/tree/develop) (see "Low-level API") to train a model from scratch or fine-tune a Huggingface model.
> 
> I'm not sure what your use case is, but if you want to adapt the segmentation or embedding model to your dataset (not reproduce the results), the best would be to fine-tune the existing models.

Thanks! 
I try to make your project work well in Chinese.I think it may be necessary to train the segmentation or embedding model in Chinese database，because Chinese and English are very different.
