### ISSUE TITLE
When I pass Audio File I get this error any ideas?

### ISSUE THREAD

**Issue by CreativeSelf0** [juanmc2005/StreamingSpeakerDiarization#23]
ValueError: Segments must not be empty.

**Comment by juanmc2005** [comment]
Hi @CreativeSelf0, could you please provide a code extract and the complete stack trace of the error? Also, what version are you using?

**Comment by CreativeSelf0** [comment]
Hey, I'm using latest version
Code Snippet:
python -m diart.demo my-own-file.wav

**Comment by juanmc2005** [comment]
I think this may be an issue with your `pyannote.core` version. Can you try with the latest version (4.3) ?

**Comment by ckliao-nccu** [comment]
I'm using `pyannote.core` version 4.3 and also having this problem.

**Comment by juanmc2005** [comment]
Ok this is related to [this line](https://github.com/pyannote/pyannote-core/blob/424b479142a2923afa639bfa1411f0d74ed97acb/pyannote/core/timeline.py#L152) in `pyannote.core` that will apparently be removed in the next version (that hasn't been released yet).

I'll add the fix and release a new version, since this is going to block all demos in v0.2.

**Comment by juanmc2005** [comment]
@CreativeSelf0 @ckliao-nccu could you please install from the branch `fix/extrude` and try again? My local run with pyannote.core 4.3 is working fine now.

**Comment by CreativeSelf0** [comment]
still no luck.
raise ValueError('Segments must not be empty.')

**Comment by juanmc2005** [comment]
@CreativeSelf0 did you install from the branch `fix/extrude`? Could you please paste the new stacktrace here so I can try to reproduce it from my end?

**Comment by ckliao-nccu** [comment]
> @CreativeSelf0 @ckliao-nccu could you please install from the branch `fix/extrude` and try again? 

I got no error using `fix/extrude`. Except for the `LightningDeprecationWarning` .

**Comment by juanmc2005** [comment]
@ckliao-nccu awesome. The warnings are normal, they come from pyannote.audio 2.0 (still in development)

**Comment by ckliao-nccu** [comment]
@juanmc2005 Thanks for your awesome work 👍

**Comment by juanmc2005** [comment]
I just released version 0.2.1 with this fix
