### ISSUE TITLE
Question about Optuna on own pipeline with segmentation model 

### ISSUE THREAD

**Issue by Shoawen0213** [juanmc2005/StreamingSpeakerDiarization#90]
hi, @juanmc2005  sorry for bothering you!
as title, I want to use optuna to tuning parameters, and the segmentation model used in pipeline is my own trained follow [training_a_model.ipynb](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb). And i have already saved in "ckpt" format
when i followed the "Custom models" part,  try to define own segmentation model like

```
class MySegmentationModel(SegmentationModel):
   def __init__(self):
        super().__init__()
        self.my_pretrained_model = torch.load("./epoch=0-step=69.ckpt")  **<- put my own ckpt here**
    def __call__(
        self,
        waveform: torch.Tensor,
        weights: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        return self.my_pretrained_model(waveform, weights)
```
then, i redefine the config like 
`config = PipelineConfig(segmentation=MySegmentationModel())`
`optimizer = Optimizer(benchmark, config, hparams, p)`
it comes out the error shown as below
![image](https://user-images.githubusercontent.com/63163334/188111023-44cd0f6e-5f44-4a22-b6b0-434d02714fa2.png)

then i trace back, and it seems that it can detect duration, sample rate, or sth
could you tell me how to fix these problems
or I can't use my segmentation model in optuna?

I want to do this because i guess the parameter will be affected in different model, so i want to give it a try

Thanks for your awesome work and help!!!
expected your response!

**Comment by juanmc2005** [comment]
Hi @Shoawen0213,

If your model was trained with pyannote, you don't need to write a custom model, I think passing the checkpoint path in `SegmentationModel.from_pyannote()` should work.

If you do need to implement a custom segmentation model, you need to override the following methods:

```python
def get_sample_rate(self) -> int:
    """Return the sample rate expected for model inputs"""

def get_duration(self) -> float:
    """Return the input duration by default (usually the one used during training)"""

def __call__(self, waveform: torch.Tensor) -> torch.Tensor:
    """Forward pass"""
```

I know that this is not very well documented and my example in the readme only concerns embedding models.
I recently started writing wiki pages to provide a better documentation of the library.

**Comment by juanmc2005** [comment]
See [custom models](https://github.com/juanmc2005/StreamingSpeakerDiarization/wiki/Custom-models)

**Comment by Shoawen0213** [comment]
hi @juanmc2005  thanks for your reply!!
I really really appreciate and am thankful for your reply!!!
i follow your kind guide [custom models](https://github.com/juanmc2005/StreamingSpeakerDiarization/wiki/Custom-models)
and the problem is solved, the ckpt file can be loaded!
But, i encounter another porblem (( sorry... :(
the error message is 
`rial 2 failed because of the following error: AttributeError("'MySegmentationModel' object has no attribute '_modules'")
`
and the whole is shown below 
![image](https://user-images.githubusercontent.com/63163334/188257785-0b61bb71-70ae-4983-bf7a-871e62bde99e.png)
![image](https://user-images.githubusercontent.com/63163334/188257799-a1778101-b14e-47ec-9a07-f40c7246fc05.png)

could you give me some hint, where should I fix this problem...?

Thanks for your help and quick, useful reply!!
It's helped me a lot!!

BTW, you mentioned that you recently started writing wiki pages to provide better documentation of the library; where can I find it? I want to give it a big thumbs up and broadcast these awesome works.

**Comment by Shoawen0213** [comment]
Hi @juanmc2005  !! My bad!! I misunderstand your suggestion! 
I follow ↓
> If your model was trained with pyannote, you don't need to write a custom model, I think passing the checkpoint path in `SegmentationModel.from_pyannote()` should work.
and I change this code by 
`segmentation: Optional[m.SegmentationModel] = SegmentationModel.from_pyannote(ckpt_path)`
in /diart/pipelines.py
and it seems to work (although I'm not sure it's that ckpt, I trace model.py)

Am i doing correct???

Thanks again!!
I'm busy cleaning due to there being a typhoon these days, this makes me a little bit tired, so that misunderstand your teaching!
BTW, if you don't mind and have times, i would like to learn from your reply about last question
Sorry about that!!

**Comment by juanmc2005** [comment]
Hi @Shoawen0213,

You shouldn't modify `pipelines.py` for this, you can just pass your own `PipelineConfig` object to `OnlineSpeakerDiarization`. If you are running `diart.tune` and not using the python API (which I think is your case) and you're also running version 0.5.1, then you should be able to do:

```shell
diart.tune ... --segmentation /path/to/checkpoint.ckpt
```

Concerning the documentation, I'm writing it as a GitHub wiki. There's a "wiki" tab in the repo's main page.
I still need to add a link from the README so it's harder to miss :)

**Comment by Shoawen0213** [comment]
Hi @juanmc2005  i finally understand what u mean!!
thanks a lot!!
